const translations = {
  en: {
    BookStoreERP: "Book Store ERP",
    newBookBtn: "New Book",
    loadDataBtn: "Load Data",
    bookHeader: "Book",
    priceHeader: "Price",
    showBookData: "Show Book Data",
    formTitle: "Add New Book",
    bookNameLabel: "Book Name",
    bookPriceLabel: "Price",
    bookImgLabel: "Image",
    bookRatingLabel: "Rating",
    submitBtn: "Add Book",
    action: "action",
    prev: "prev",
    next: "next",
    edit: "Edit",
    rating: "rating",
    changeLang: "change language",
    bookImageLabel: "Image",
    NoBookFound: "No Book Found",
  },
  he: {
    BookStoreERP: "חנות ספרים",
    newBookBtn: "ספר חדש",
    loadDataBtn: "טען נתונים",
    bookHeader: "ספר",
    priceHeader: "מחיר",
    showBookData: "הצג פרטי ספר",
    formTitle: "הוסף ספר חדש",
    bookNameLabel: "שם הספר",
    bookPriceLabel: "מחיר",
    bookImgLabel: "תמונה",
    bookRatingLabel: "דירוג",
    submitBtn: "הוסף ספר",
    action: "פעולה",
    prev: "הקודם",
    next: "הבא",
    edit: "ערוך",
    changeLang: "שנה שפה",
    bookImageLabel: "תמונה",
    NoBookFound: "לא נמצאו ספרים",
    rating: "דירוג",
  },
};
